export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const INCREASE_COUNT = "INCREASE_COUNT";
export const DECREASE_COUNT = "DECREASE_COUNT";
export const SLOW_INCREASE = "SLOW_INCREASE";
export const SLOW_DECREASE = "SLOW_DECREASE";
